### ISSUE TITLE
where is the regulator to remove?

### ISSUE THREAD

**Issue by jduffas** [Brezensalzer/ble_sensor_adv#1]
Hello,
Could you tell more about where is the regulator to remove?
an other point, you tell about 2,7uA, but the photo show your multimeter with 2,7 on screen, but volts are selected...
so I think it's not the good photo to illustrate.

and, it would have ben great to have consumption figures about différence,  between with/without led and with/without regulator.

thank you :-)

**Comment by Brezensalzer** [comment]
Hi,

please think about twice before partially destroying your Itsybitsy...
I've used the same software strategy with a Seeed Xiao BLE without removing any parts, have a look: https://github.com/Brezensalzer/ble_xiao_adv
But if you really want to, the AP2112 regulator is on the backside of the Itsybitsy. It is the 5 pin IC close to the A0 label.
See https://learn.adafruit.com/assets/86933

You can't measure µA with a cheap multimeter, you need a special circuitry like the "tinyCurrent" on the second picture. It translates 1 µA to 1 mV on the multimeter.

I2C breakout board always powered: ~ 1.5 mA
DotStar LED: ~ 0.4 mA 
Regulator: ~ 0.7 mA if board is powered directly via 3V pin

Softmodem: ~0,28 mA if bluetooth is enabled... that's a Arduino specific problem, I could'nt switch it off once initialized

Bye

**Comment by jduffas** [comment]
Hi,Thank’s a lot for your answer :-)
I actually have a XIAO BLE, I will try your code,I actually manage to have a 0,7mA minimum with the soft reset, witch is better as before (I had 1,5mA) but not still good.
I will receive my itsybitsy soon, I won’t destroy it at the beginning if I can get a correct consumption.
Have a good day and thank you again
